spring.application.name=pokemon-api

# H2 Database settings
spring.datasource.url=jdbc:h2:mem:pokemondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Hibernate / JPA settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# Jackson config to format dates consistently
spring.jackson.date-format=yyyy/MM/dd
spring.jackson.serialization.write-dates-as-timestamps=false
